AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB tables for AI Agent Platform

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-UserTable'
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexUpdates:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL  # Adjust projection as needed
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  AgentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-AgentTable'
      AttributeDefinitions:
        - AttributeName: agentId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: agentId
          KeyType: HASH
      GlobalSecondaryIndexUpdates:
        - IndexName: UserAgentIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: agentId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL # Adjust projection as needed
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  LoginTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-LoginTable'
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  DynamoDBTableName:
    Description: The name of the DynamoDB table
    Value: !Ref UserTable
  DynamoDBTableArn:
    Description: The ARN of the DynamoDB table
    Value: !GetAtt UserTable.Arn