AWSTemplateFormatVersion: '2010-09-09'
Description: Main template for Agent Platform
Parameters:
  AWSRegion:
    Type: String
    Default: us-west-1
  KeycloakClientSecret:
    Type: String
    Default: ''
  KeycloakAdminPassword:
    Type: String
    Default: ''
  GitHubUsername:
    Type: String
    Default: guanmasons
  GitHubRepo:
    Type: String
    Default: agent-platform
Resources:
  DynamoDBTables:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-art/c50a312224932f0fa0432c50ac03c596.template
      TimeoutInMinutes: 10
  EC2Instance:
    Type: AWS::CloudFormation::Stack
    DependsOn: DynamoDBTables
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-art/2f66679d0a4491973843e82e6d9dfb8e.template
      Parameters:
        DynamoDBTableArns:
          Fn::Join:
          - ','
          - - Fn::GetAtt:
              - DynamoDBTables
              - Outputs.DynamoDBTableArn
            - Fn::GetAtt:
              - DynamoDBTables
              - Outputs.AgentDynamoDBTableArn
            - Fn::GetAtt:
              - DynamoDBTables
              - Outputs.LoginDynamoDBTableArn
        KeycloakClientSecret:
          Ref: KeycloakClientSecret
        KeycloakAdminPassword:
          Ref: KeycloakAdminPassword
        GitHubUsername:
          Ref: GitHubUsername
        GitHubRepo:
          Ref: GitHubRepo
Outputs:
  EC2InstanceId:
    Description: The ID of the EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - Outputs.EC2InstanceId
  DynamoDBTableName:
    Description: The name of the DynamoDB table
    Value:
      Fn::GetAtt:
      - DynamoDBTables
      - Outputs.DynamoDBTableName
  EC2InstancePublicDNS:
    Description: Public DNS of the EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - Outputs.EC2InstancePublicDNS
  EC2InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - Outputs.EC2InstancePublicIP
