AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB tables for AI Agent Platform
Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${AWS::StackName}-UserTable
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  AgentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${AWS::StackName}-AgentTable
      AttributeDefinitions:
      - AttributeName: agentId
        AttributeType: S
      KeySchema:
      - AttributeName: agentId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  LoginTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${AWS::StackName}-LoginTable
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:
  DynamoDBTableName:
    Description: The name of the User DynamoDB table
    Value:
      Ref: UserTable
  DynamoDBTableArn:
    Description: The ARN of the User DynamoDB table
    Value:
      Fn::GetAtt:
      - UserTable
      - Arn
  AgentDynamoDBTableName:
    Description: The name of the Agent DynamoDB table
    Value:
      Ref: AgentTable
  AgentDynamoDBTableArn:
    Description: The ARN of the Agent DynamoDB table
    Value:
      Fn::GetAtt:
      - AgentTable
      - Arn
  LoginDynamoDBTableName:
    Description: The name of the Login DynamoDB table
    Value:
      Ref: LoginTable
  LoginDynamoDBTableArn:
    Description: The ARN of the Login DynamoDB table
    Value:
      Fn::GetAtt:
      - LoginTable
      - Arn
