version: '3.8'
services:
  datastore-api:
    build:
      context: ../../services/datastore-api
      dockerfile: Dockerfile
    ports:
      - "${DATASTORE_API_PORT:-3001}:${DATASTORE_API_PORT:-3001}"
    environment:
      SERVICE_PORT: ${DATASTORE_API_PORT:-3001}
      SERVICE_REGION: ${AWS_REGION}
      DYNAMODB_USER_TABLE: agent-platform-UserTable
      DYNAMODB_AGENT_TABLE: agent-platform-AgentTable
      DYNAMODB_USER_LOGIN_TABLE: agent-platform-LoginTable
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    networks:
      - agent-platform-network

  control-api:
    build:
      context: ../../services/control-api
      dockerfile: Dockerfile
    ports:
      - "${CONTROL_API_PORT:-3002}:${CONTROL_API_PORT:-3002}"
    environment:
      SERVICE_PORT: ${CONTROL_API_PORT:-3002}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      DATASTORE_API_URL: http://datastore-api:${DATASTORE_API_PORT:-3001}
    depends_on:
      - datastore-api
      - keycloak
    networks:
      - agent-platform-network

  web-service:
    build:
      context: ../../services/web-service
      dockerfile: Dockerfile
    ports:
      - "${WEB_SERVICE_PORT:-3000}:${WEB_SERVICE_PORT:-3000}"
    environment:
      REACT_APP_CONTROL_API_URL: http://${EC2_PUBLIC_IP:-localhost}:${CONTROL_API_PORT:-3002}
      REACT_APP_KEYCLOAK_URL: http://${EC2_PUBLIC_IP:-localhost}:8080
      REACT_APP_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      REACT_APP_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_WEB_CLIENT_ID}
    depends_on:
      - control-api
    networks:
      - agent-platform-network

  keycloak:
    build:
      context: ../../services/keycloak
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    networks:
      - agent-platform-network

networks:
  agent-platform-network:
    driver: bridge