version: '3.8'

services:
  datastore-api:
    build:
      context: ../../services/datastore-api
      dockerfile: Dockerfile
    environment:
      - AWS_REGION=local
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - DATASTORE_API_PORT=3001
      - DYNAMODB_USER_TABLE=local-users
      - DYNAMODB_AGENT_TABLE=local-agents
      - DYNAMODB_USER_LOGIN_TABLE=local-logins
    ports:
      - "3001:3001"
    networks:
      - internal

  control-api:
    build:
      context: ../../services/control-api
      dockerfile: Dockerfile
    environment:
      - CONTROL_API_PORT=3002
      - DATASTORE_API_URL=http://datastore-api:3001
    ports:
      - "3002:3002"
    depends_on:
      - datastore-api
    networks:
      - internal

  keycloak:
    build:
      context: ../../services/keycloak
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=localhost
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_IMPORT=/opt/keycloak/data/import/realm-config.json
    ports:
      - "8080:8080"
    volumes:
      - ../../services/keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json
    networks:
      - internal
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]

  web-service:
    build:
      context: ../../services/web-service
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:3002
    ports:
      - "80:80"
    depends_on:
      - control-api
    networks:
      - internal

networks:
  internal:
    driver: bridge