services:
  datastore-api:
    build:
      context: ../../services/datastore-api
      dockerfile: Dockerfile
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DATASTORE_API_PORT=3001
      - DYNAMODB_USER_TABLE=${DYNAMODB_USER_TABLE}
      - DYNAMODB_AGENT_TABLE=${DYNAMODB_AGENT_TABLE}
      - DYNAMODB_USER_LOGIN_TABLE=${DYNAMODB_USER_LOGIN_TABLE}
    expose:
      - "3001"
    networks:
      internal:
        aliases:
          - datastore-api

  control-api:
    build:
      context: ../../services/control-api
      dockerfile: Dockerfile
    environment:
      - CONTROL_API_PORT=3002
      - DATASTORE_API_URL=http://datastore-api:3001
    expose:
      - "3002"
    depends_on:
      - datastore-api
    networks:
      internal:
        aliases:
          - control-api

  keycloak:
    build:
      context: ../../services/keycloak
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    expose:
      - "8080"
    networks:
      internal:
        aliases:
          - keycloak

  web-service:
    build:
      context: ../../services/web-service
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:3002
    ports:
      - "80:80"
    depends_on:
      - control-api
    networks:
      - internal
      - external
    environment:
      - NODE_ENV=production

networks:
  internal:
    internal: true
  external:
    internal: false