version: '3.8'

services:
  datastore-api:
    build:
      context: ../../services/datastore-api
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "${DATASTORE_API_PORT}:${DATASTORE_API_PORT}"
    networks:
      - agent-platform-network

  control-api:
    build:
      context: ../../services/control-api
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "${CONTROL_API_PORT}:${CONTROL_API_PORT}"
    depends_on:
      - datastore-api
      - keycloak
    networks:
      - agent-platform-network

  web-service:
    build:
      context: ../../services/web-service
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "${WEB_SERVICE_PORT}:${WEB_SERVICE_PORT}"
    depends_on:
      - control-api
    networks:
      - agent-platform-network

  keycloak:
    build:
      context: ../../services/keycloak
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "8080:8080"
    networks:
      - agent-platform-network

networks:
  agent-platform-network:
    driver: bridge